name: "Rolladex"

services:
    db:
        image: postgres:18.4-alpine
        container_name: rolladex-db
        environment:
            PGUSER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        volumes:
            - db-data:/var/lib/rolladex
        healthcheck:
            test: ["CMD", "pg_isready"]
            interval: 10s
            timeout: 5s
            retries: 5
        ports:
            - "3001:5432"

    # backup:
    #     image: postgres:18.4-alpine
    #     container_name: rolladex-db-backup

    # api:
    #     build:
    #         context: ./api
    #         target: base
    #     container_name: rolladex-api
    #     depends_on:
    #         db:
    #             condition: service_healthy
    #     env_file:
    #         - .env
    #     ports:
    #         - "3002:3001"
    #     environment:
    #         - DB_HOST=${DB_HOST}
    #         - DB_PORT=${DB_PORT}

volumes:
    db-data:
