
CREATE TABLE IF NOT EXISTS "Images" (
	"id" INTEGER NOT NULL UNIQUE,
	"filepath" TEXT,
	"created_at" DATETIME DEFAULT CURRENT_TIMESTAMP,
	"updated_at" DATETIME DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY("id")
);

CREATE TABLE IF NOT EXISTS "NotificationPreferences" (
	"id" INTEGER NOT NULL UNIQUE,
	"email" BOOLEAN,
	"sms" BOOLEAN,
	"pushNotification" BOOLEAN,
	PRIMARY KEY("id")
);

CREATE TABLE IF NOT EXISTS "Users" (
	"id" INTEGER NOT NULL UNIQUE,
	"username" TEXT NOT NULL UNIQUE,
	"passwordHash" TEXT NOT NULL,
	"passwordSalt" TEXT NOT NULL,
	"email" TEXT UNIQUE,
	"profile_image_id" INTEGER,
	"birthday" TEXT,
	"created_at" DATETIME DEFAULT CURRENT_TIMESTAMP,
	"updated_at" DATETIME DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY("id"),
	FOREIGN KEY ("profile_image_id") REFERENCES "Images"("id")
	ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS "Friends" (
	"id" INTEGER NOT NULL UNIQUE,
	"name" TEXT NOT NULL,
	"birthday" TEXT,
	"profile_image_id" INTEGER,
	"created_at" DATETIME DEFAULT CURRENT_TIMESTAMP,
	"updated_at" DATETIME DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY("id"),
	FOREIGN KEY ("profile_image_id") REFERENCES "Images"("id")
	ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS "UsersFriends" (
	"id" INTEGER NOT NULL UNIQUE,
	"user_id" INTEGER NOT NULL,
	"friend_id" INTEGER NOT NULL,
	"created_at" DATETIME DEFAULT CURRENT_TIMESTAMP,
	"updated_at" DATETIME DEFAULT CURRENT_TIMESTAMP,
	"relationship_status" TEXT,
	PRIMARY KEY("id"),
	FOREIGN KEY ("friend_id") REFERENCES "Friends"("id")
	ON UPDATE NO ACTION ON DELETE CASCADE,
	FOREIGN KEY ("user_id") REFERENCES "Users"("id")
	ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS "Interactions" (
	"id" INTEGER NOT NULL UNIQUE,
	"date" TEXT NOT NULL,
	"user_id" INTEGER NOT NULL,
	"friend_id" INTEGER NOT NULL,
	"interaction_type" VARCHAR,
	"created_at" DATETIME DEFAULT CURRENT_TIMESTAMP,
	"updated_at" DATETIME DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY("id"),
	FOREIGN KEY ("user_id") REFERENCES "Users"("id")
	ON UPDATE NO ACTION ON DELETE CASCADE,
	FOREIGN KEY ("friend_id") REFERENCES "Friends"("id")
	ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS "Meetups" (
	"id" INTEGER NOT NULL UNIQUE,
	"date" TEXT NOT NULL,
	"location" TEXT,
	"name" TEXT,
	"organizer_id" INTEGER,
	"created_at" DATETIME DEFAULT CURRENT_TIMESTAMP,
	"updated_at" DATETIME DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY("id"),
	FOREIGN KEY ("organizer_id") REFERENCES "Users"("id")
	ON UPDATE NO ACTION ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "MeetupsAttendees" (
	"id" INTEGER NOT NULL UNIQUE,
	"meetup_id" INTEGER,
	"friend_id" INTEGER,
	"created_at" DATETIME DEFAULT CURRENT_TIMESTAMP,
	"updated_at" DATETIME DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY("id"),
	FOREIGN KEY ("meetup_id") REFERENCES "Meetups"("id")
	ON UPDATE NO ACTION ON DELETE CASCADE,
	FOREIGN KEY ("friend_id") REFERENCES "Friends"("id")
	ON UPDATE NO ACTION ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "UserSettings" (
	"id" INTEGER NOT NULL UNIQUE,
	"user_id" INTEGER,
	"NotificationPreferences_id" INTEGER,
	"ui_theme" VARCHAR,
	"created_at" DATETIME DEFAULT CURRENT_TIMESTAMP,
	"updated_at" DATETIME DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY("id"),
	FOREIGN KEY ("user_id") REFERENCES "Users"("id")
	ON UPDATE NO ACTION ON DELETE NO ACTION,
	FOREIGN KEY ("NotificationPreferences_id") REFERENCES "NotificationPreferences"("id")
	ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS "Sessions" (
	"id" INTEGER NOT NULL UNIQUE,
	"user_id" INTEGER NOT NULL,
	"session_token" TEXT NOT NULL,
	"created_at" DATETIME DEFAULT CURRENT_TIMESTAMP,
	"expires_at" DATETIME,
	"is_revoked" BOOLEAN,
	PRIMARY KEY("id"),
	FOREIGN KEY ("user_id") REFERENCES "Users"("id")
	ON UPDATE NO ACTION ON DELETE CASCADE
);
